# Generated by Django 3.1.1 on 2020-09-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test_abstract_object', max_length=50)),
            ],
            options={
                'db_table': 'abstract_models',
                'default_permissions': (),
            },
        ),
    ]
